DROP TABLE [dbo].[treset_password_apply];
CREATE TABLE [dbo].[treset_password_apply] (
[id] varchar(64) NOT NULL ,
[entity_code] varchar(64) NULL ,
[entity_name] varchar(64) NULL ,
[attach] varchar(200) NULL ,
[mobile] varchar(64) NULL ,
[email] varchar(64) NULL ,
[apply_date] datetime NULL ,
[approve_date] datetime NULL ,
[approve_opinion] varchar(100) NULL,
[status] char(1) NULL,
[create_by] varchar(32) NULL ,
[update_by] varchar(32) NULL ,
[create_date] datetime NULL ,
[update_date] datetime NULL ,
[remarks] varchar(200) NULL ,
[del_flag] char(1) NULL,
[proc_ins_id] varchar(50) NULL
);

DROP TABLE [dbo].[corp_basic_info_application];
CREATE TABLE [dbo].[corp_basic_info_application] (
[id] int NOT NULL IDENTITY(1,1) ,
[qyID] varchar(100) NOT NULL ,
[UserID] varchar(100) NULL ,
[qymc] nvarchar(100) NULL ,
[zzjgdm] varchar(50) NULL ,
[yyzzzch] varchar(50) NULL ,
[khyh] nvarchar(100) NULL ,
[yhzh] varchar(50) NULL ,
[sfsyq] char(1) NULL ,
[gcjsry_zs] int NULL ,
[gcjsry_gjzcrs] int NULL ,
[gcjsry_zjzcrs] int NULL ,
[sylxID] int NULL ,
[sylx] nvarchar(8) NULL ,
[ProvinceID] varchar(20) NULL ,
[Province] nvarchar(20) NULL ,
[CityID] varchar(20) NULL ,
[City] nvarchar(20) NULL ,
[CountyID] varchar(20) NULL ,
[County] nvarchar(20) NULL ,
[zcdd] nvarchar(100) NULL ,
[jjxzID] int NULL ,
[jjxz] nvarchar(50) NULL ,
[zczb] varchar(50) NULL ,
[zyfw] nvarchar(MAX) NULL ,
[jyfw] nvarchar(MAX) NULL ,
[clrq] datetime NULL ,
[qyjj] nvarchar(MAX) NULL ,
[xxdd] nvarchar(200) NULL ,
[yzbm] varchar(20) NULL ,
[cz] varchar(50) NULL ,
[email] varchar(100) NULL ,
[webAddress] varchar(100) NULL ,
[lxr] nvarchar(50) NULL ,
[lxdh] varchar(50) NULL ,
[fddbr_ryid] nvarchar(100) NULL ,
[fddbr] nvarchar(25) NULL ,
[qyfzr_ryid] nvarchar(100) NULL ,
[qyfzr] nvarchar(25) NULL ,
[cwfzr_ryid] nvarchar(100) NULL ,
[cwfzr] nvarchar(25) NULL ,
[jsfzr_ryid] nvarchar(100) NULL ,
[jsfzr] nvarchar(25) NULL ,
[aqfzr_ryid] nvarchar(100) NULL ,
[aqfzr] nvarchar(25) NULL ,
[DataState] int NULL ,
[tag] varchar(50) NULL ,
[xgr] nvarchar(100) NULL ,
[xgrqsj] datetime NULL ,
[xmjlzs] int NULL ,
[aqy] int NULL ,
[zjy] int NULL ,
[sgy] int NULL ,
[tyshxydm] varchar(50) NULL ,
[type] char(1) NULL DEFAULT ('1') ,
[proc_ins_id] varchar(50) NULL,
[photo] varchar(200) NULL ,
[approve_opinion]  varchar(100) NULL,
[password] varchar(50) NULL,
Primary key(id)
);